%% Unconstrained Delegation
sequenceDiagram

actor User

User->>DC: KRB_AS_REQ
DC->>User: KRB_AS_REP
Note right of User: User obtains TGT
User->>DC: KRB_TGS_REQ
DC->>User: KRB_TGS_REP
Note right of User: User obtains ST for User to Service
Note right of User: The ST contains a copy of the User TGT

User->>Service: KRB_AP_REQ
Note left of Service: Service obtains User's TGT
Service->>User: KRB_AP_REP

Service->>DC: KRB_TGS_REQ (using User's TGT)
DC->>Service: KRB_TGS_REP
Note left of Service: Service obtains ST for User to Resource

Note right of Service: Authenticates as User
Service->>Resource: KRB_AP_REQ
Resource->>Service: KRB_AP_REP
